### ISSUE TITLE
Database Connection Issue on Online order processing during pandemics for Db2 connection with Watson Assistant.

### ISSUE THREAD

**Issue by charlie-2201** [IBM/online_order_processing_during_pandemics#5]
@jjasghar @christo4ferris @stevemar @maheshwarishikha @johnwalicki 
We are working on Online order processing during pandemics for Db2 connection with Watson Assistant.
We are facing the problem with the connection of Database.
Following are the errors:
2022-01-05T13:58:03.72+0530 [HEALTH/0] ERR Failed to make TCP connection to port 8080: connection refused
2022-01-05T13:58:03.72+0530 [CELL/0] ERR Failed after 1m3.784s: readiness health check never passed.

2022-01-05T13:58:47.89+0530 [APP/PROC/WEB/0] ERR Traceback (most recent call last):
2022-01-05T13:58:47.89+0530 [APP/PROC/WEB/0] ERR File "app.py", line 26, in
2022-01-05T13:58:47.89+0530 [APP/PROC/WEB/0] ERR dsn_database = credentials1['db']
2022-01-05T13:58:47.89+0530 [APP/PROC/WEB/0] ERR KeyError: 'db'

If its possible then can we have a meeting after 3:30 PM IST

**Comment by johnwalicki** [comment]
Hi @charlie-2201  - Did you create the DB2 instance (watch the animated GIF in Step 6) and then add the DB2 credentials to the `ibm-db2-credentials.json` (Step 7) ?

**Comment by charlie-2201** [comment]
Yes, but the problem is still same.
I got the error that we are not able to initialize the database.

**Comment by johnwalicki** [comment]
There is nothing magical about line 26 in app.py where it is failing.   It parses the dict and gets the `db` value.  Are you certain there is a db in your `ibm-db2-credentials.json` ?  See the second part of Step 7.

A snippet of my DB2 credential file looks like this:
```
    "db2": {
      "authentication": {
        "method": "direct",
        "password": "secret",
        "username": "user"
      },
```

**Comment by charlie-2201** [comment]
Yes it is

**Comment by johnwalicki** [comment]
It still sounds like your json file is corrupted.
Can you send me your ibm-db2-credentials.json file? Blank the username, password values before sending it. Walicki @ us.ibm.com

**Comment by manojjahgirdar** [comment]
The issue has been fixed. Please clone the repo once again to get the changes. Here is more details on the PR #6. Thanks.

**Comment by charlie-2201** [comment]
Can you help me fix this issue @manojjahgirdar 
This is the route link that got created
https://covid-19-help-desk-fantastic-roan-jp.mybluemix.net/
